"""Initial schema

Revision ID: 6856da7bc07d
Revises:
Create Date: 2026-03-07 03:39:33.867306

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6856da7bc07d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "begda", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column(
            "endda",
            sa.Date(),
            server_default=sa.text("DATE '9999-12-31'"),
            nullable=False,
        ),
        sa.Column("exercise_name", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("exercise_id"),
        sa.UniqueConstraint(
            "user_id", "exercise_name", "endda", name="uq_user_endda_exercise_name"
        ),
    )
    op.create_table(
        "routines",
        sa.Column("routine_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("routine_name", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("routine_id"),
        sa.UniqueConstraint("user_id", "routine_name", name="uq_user_routine_name"),
    )
    op.create_table(
        "routines_exercises",
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("routine_id", sa.Integer(), nullable=False),
        sa.Column("exercise_index", sa.Integer(), nullable=False),
        sa.Column("planned_sets", sa.Integer(), nullable=False),
        sa.Column("exercise_notes", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["exercises.exercise_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["routine_id"], ["routines.routine_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("exercise_id", "routine_id"),
        sa.UniqueConstraint(
            "routine_id",
            "exercise_index",
            deferrable=True,
            initially="IMMEDIATE",
            name="uq_routine_exercise_order",
        ),
    )
    op.create_table(
        "workouts",
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("routine_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("workout_name", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["routine_id"], ["routines.routine_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workout_id"),
    )
    op.create_table(
        "workouts_exercises",
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("exercise_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["exercises.exercise_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"], ["workouts.workout_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("workout_id", "exercise_id"),
        sa.UniqueConstraint(
            "workout_id",
            "exercise_index",
            deferrable=True,
            initially="IMMEDIATE",
            name="uq_workout_exercise_order",
        ),
    )
    op.create_table(
        "workouts_sets",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["workout_id", "exercise_id"],
            ["workouts_exercises.workout_id", "workouts_exercises.exercise_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("set_id"),
        sa.UniqueConstraint(
            "workout_id",
            "exercise_id",
            "set_index",
            name="uq_set_per_exercise_per_workout",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workouts_sets")
    op.drop_table("workouts_exercises")
    op.drop_table("workouts")
    op.drop_table("routines_exercises")
    op.drop_table("routines")
    op.drop_table("exercises")
    # ### end Alembic commands ###
