"""Initial Schema

Revision ID: 6afdcef38777
Revises:
Create Date: 2026-04-20 01:07:24.668369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6afdcef38777"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "begda", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column(
            "endda",
            sa.Date(),
            server_default=sa.text("DATE '9999-12-31'"),
            nullable=False,
        ),
        sa.Column("exercise_name", sa.String(length=36), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("user_id"), "="),
            (sa.column("exercise_name"), "="),
            (sa.text("daterange(begda, endda, '[)')"), "&&"),
            using="gist",
            name="exclude_exercise_overlap",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("exercise_id"),
    )
    op.create_table(
        "routines",
        sa.Column("routine_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("routine_name", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("routine_id"),
        sa.UniqueConstraint("user_id", "routine_name", name="uq_user_routine_name"),
    )
    op.create_table(
        "routines_exercises",
        sa.Column("routine_id", sa.Integer(), nullable=False),
        sa.Column("planned_sets", sa.Integer(), nullable=False),
        sa.Column("exercise_notes", sa.String(length=128), nullable=True),
        sa.Column("exercise_index", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["exercises.exercise_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["routine_id"], ["routines.routine_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("exercise_id", "routine_id"),
        sa.UniqueConstraint(
            "routine_id",
            "exercise_index",
            deferrable=True,
            initially="IMMEDIATE",
            name="uq_routine_exercise_order",
        ),
    )
    op.create_table(
        "workouts",
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("routine_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("workout_name", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["routine_id"], ["routines.routine_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workout_id"),
    )
    op.create_table(
        "workouts_exercises",
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_index", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["exercises.exercise_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"], ["workouts.workout_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("workout_id", "exercise_id"),
        sa.UniqueConstraint(
            "workout_id",
            "exercise_index",
            deferrable=True,
            initially="IMMEDIATE",
            name="uq_workout_exercise_order",
        ),
    )
    op.create_table(
        "workouts_sets",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["workout_id", "exercise_id"],
            ["workouts_exercises.workout_id", "workouts_exercises.exercise_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("set_id"),
        sa.UniqueConstraint(
            "workout_id",
            "exercise_id",
            "set_index",
            name="uq_set_per_exercise_per_workout",
        ),
    )
    # ### end Alembic commands ###
    op.execute("DROP POLICY IF EXISTS user_access_their_data ON exercises")
    op.execute("ALTER TABLE exercises ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
    CREATE POLICY user_access_their_data
    ON exercises
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
    """
    )

    op.execute("DROP POLICY IF EXISTS user_access_their_data ON routines")
    op.execute("ALTER TABLE routines ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
    CREATE POLICY user_access_their_data
    ON routines
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
    """
    )

    op.execute("DROP POLICY IF EXISTS user_access_their_data ON routines_exercises")
    op.execute("ALTER TABLE routines_exercises ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
    CREATE POLICY user_access_their_data
    ON routines_exercises
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (
        EXISTS (
            SELECT 1
            FROM exercises e
            WHERE e.exercise_id = routines_exercises.exercise_id
              AND auth.uid() = e.user_id
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM exercises e
            WHERE e.exercise_id = routines_exercises.exercise_id
              AND auth.uid() = e.user_id
        )
    );
    """
    )

    op.execute("DROP POLICY IF EXISTS user_access_their_data ON workouts")
    op.execute("ALTER TABLE workouts ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
    CREATE POLICY user_access_their_data
    ON workouts
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
    """
    )

    op.execute("DROP POLICY IF EXISTS user_access_their_data ON workouts_exercises")
    op.execute("ALTER TABLE workouts_exercises ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
    CREATE POLICY user_access_their_data
    ON workouts_exercises
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (
        EXISTS (
            SELECT 1
            FROM exercises e
            WHERE e.exercise_id = workouts_exercises.exercise_id
              AND auth.uid() = e.user_id
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM exercises e
            WHERE e.exercise_id = workouts_exercises.exercise_id
              AND auth.uid() = e.user_id
        )
    );
    """
    )

    op.execute("DROP POLICY IF EXISTS user_access_their_data ON workouts_sets")
    op.execute("ALTER TABLE workouts_sets ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
    CREATE POLICY user_access_their_data
    ON workouts_sets
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (
        EXISTS (
            SELECT 1
            FROM exercises e
            WHERE e.exercise_id = workouts_sets.exercise_id
              AND auth.uid() = e.user_id
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM exercises e
            WHERE e.exercise_id = workouts_sets.exercise_id
              AND auth.uid() = e.user_id
        )
    );
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS user_access_their_data ON exercises")
    op.execute("DROP POLICY IF EXISTS user_access_their_data ON routines")
    op.execute("DROP POLICY IF EXISTS user_access_their_data ON routines_exercises")
    op.execute("DROP POLICY IF EXISTS user_access_their_data ON workouts")
    op.execute("DROP POLICY IF EXISTS user_access_their_data ON workouts_exercises")
    op.execute("DROP POLICY IF EXISTS user_access_their_data ON workouts_sets")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workouts_sets")
    op.drop_table("workouts_exercises")
    op.drop_table("workouts")
    op.drop_table("routines_exercises")
    op.drop_table("routines")
    op.drop_table("exercises")
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS btree_gist")
